### ISSUE TITLE
Beta downloads page acting weird

### ISSUE THREAD

**Issue by AwesomeTech10** [dothq/dothq.co#11]
Whenever switching between light theme and dark theme on the beta downloads page, the number of downloads loading changes. For example, if there are 4 downloads loading (nothing available yet, just the loading images) and I switch to the dark theme, there will be 2 downloads loading.

**Comment by tandpfun** [comment]
I have experienced this issue as well, but instead, just every time I reload the page.

**Comment by EnderDev** [comment]
Hi, that's a skeleton loader. Many sites like YouTube and Facebook use them to placeholder data while they wait for the real data to load. I will however look into the number of downloads changing on theme change, that is a little strange.

Thanks, Kieran
