### ISSUE TITLE
GitHub link in footer isn't updated (?)

### ISSUE THREAD

**Issue by ArashNrIm** [dothq/dothq.co#18]
Hello there!

While browsing the dothq.co website, I noticed that the GitHub link in the footer wasn't updated (directs to https://github.com/GitHub, expected https://github.com/dothq). The screenshot below shows this occurring:

<img width="1403" alt="Screenshot 2020-07-05 at 4 50 49 PM" src="https://user-images.githubusercontent.com/47273556/86529007-af85fe00-bedf-11ea-89e0-60b6ce3154c0.png">

If this is indeed a small error, I'd like to request to create a pull request to change the link; this will make the site just a little better and more consistent (matching the GitHub link at the top). Thanks!

**Comment by EnderDev** [comment]
Hi there,

Thanks for bringing this to our attention, it is indeed an error. If you want to make a PR to fix this, feel free.

Thanks.

**Comment by ArashNrIm** [comment]
Thanks! I'll work on it and create a PR once done.

**Comment by ArashNrIm** [comment]
Thanks for merging!
