### ISSUE TITLE
Download buttons are broken.

### ISSUE THREAD

**Issue by Blakeinstein** [dothq/dothq.co#25]
## Expected Behavior
The corresponding binaries/setup files should begin downloading on pressing download

## Actual Behavior
Nothing happens. Both https://dothq.co/download and https://dothq.co/download/dot have dead download buttons.

## Steps to Reproduce the Problem

  1. Go to https://dothq.co/download or https://dothq.co/download/dot
  2. Press download
  3. ???
  4. Loss?

## Specifications

  - Browser: Firefox v81.0 (64-bit)
  - Platform: Windows 10 2004 v19041.508

**Comment by Blakeinstein** [comment]
Turns out even register is broken. Express server down?

**Comment by EnderDev** [comment]
Hi there, the new website is still a work in progress and downloads are not currently available (as stated on the landing page)
